'use client';

import { Button, Notice, Panel } from '@/components/ui';
import { apiFetch } from '@/lib/api';
import { useRouter, useSearchParams } from 'next/navigation';
import { FormEvent, Suspense, useState } from 'react';

function ResetForm() { const router = useRouter(); const params = useSearchParams(); const [token, setToken] = useState(params.get('token') || ''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { await apiFetch('/auth/reset-password', { method: 'POST', body: JSON.stringify({ token, newPassword: password }) }); setMessage('Senha redefinida com sucesso.'); setTimeout(() => router.push('/login'), 900); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Token inválido.'); } finally { setLoading(false); } } return <main className="mx-auto max-w-lg px-5 py-16"><Panel className="p-7 md:p-10"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-300">Segurança da conta</p><h1 className="mt-2 font-display text-4xl font-bold">Defina uma nova senha</h1><form onSubmit={submit} className="mt-8 space-y-5"><label className="block"><span className="field-label">Token de recuperação</span><input className="field-control" required value={token} onChange={e => setToken(e.target.value)} /></label><label className="block"><span className="field-label">Nova senha</span><input className="field-control" type="password" minLength={8} required value={password} onChange={e => setPassword(e.target.value)} /></label>{error ? <Notice kind="error">{error}</Notice> : null}{message ? <Notice kind="success">{message}</Notice> : null}<Button type="submit" loading={loading} className="w-full">Salvar nova senha</Button></form></Panel></main>; }
export default function ResetPage() { return <Suspense fallback={<main className="p-12 text-center">Carregando...</main>}><ResetForm /></Suspense>; }
