'use client';

import { Button, Panel } from '@/components/ui';
import { apiFetch } from '@/lib/api';
import { User } from '@/types';
import { useEffect, useState } from 'react';

export function CommercialAdminPanel() {
  const [students, setStudents] = useState<User[]>([]); const [feedbacks, setFeedbacks] = useState<any[]>([]); const [selected, setSelected] = useState(''); const [title, setTitle] = useState('Planilha oficial'); const [url, setUrl] = useState(''); const [notice, setNotice] = useState('');
  async function load() { const [users, feedback] = await Promise.all([apiFetch<{ users: User[] }>('/users?role=STUDENT'), apiFetch<{ feedbacks: any[] }>('/feedbacks')]); setStudents(users.users); setFeedbacks(feedback.feedbacks); }
  useEffect(() => { void load().catch(() => undefined); }, []);
  async function remove(id: string) { if (!window.confirm('Excluir este aluno e seus dados?')) return; await apiFetch(`/students/${id}`, { method: 'DELETE' }); setStudents(current => current.filter(item => item.id !== id)); }
  async function addSheet() { if (!selected || !url) return; await apiFetch('/spreadsheets', { method: 'POST', body: JSON.stringify({ userId: selected, title, externalUrl: url }) }); setNotice('Planilha vinculada com sucesso.'); setUrl(''); }
  return <div className="mt-7 grid gap-7 lg:grid-cols-2"><Panel className="p-6"><div className="flex items-center justify-between"><h2 className="font-display text-2xl font-bold">Gestão de alunos</h2><span className="rounded-full bg-ink px-3 py-1 text-xs font-bold text-lime-300">{students.length}</span></div><div className="mt-5 space-y-3">{students.map(student => <div key={student.id} className="flex items-center justify-between rounded-2xl border border-ink/10 p-4"><div><p className="font-bold">{student.name}</p><p className="text-xs text-ink/50">{student.email} · {student.gender === 'FEMALE' ? 'Feminino' : 'Masculino'}</p><p className="text-xs font-bold text-lime-700">Assinatura: {student.subscriptionStatus}</p></div><Button variant="ghost" onClick={() => remove(student.id)}>Excluir</Button></div>)}</div></Panel><Panel className="p-6"><h2 className="font-display text-2xl font-bold">Planilhas e feedbacks</h2><div className="mt-5 space-y-3"><select className="field-control" value={selected} onChange={e => setSelected(e.target.value)}><option value="">Selecione um aluno</option>{students.map(student => <option key={student.id} value={student.id}>{student.name}</option>)}</select><input className="field-control" value={title} onChange={e => setTitle(e.target.value)} placeholder="Título" /><input className="field-control" value={url} onChange={e => setUrl(e.target.value)} placeholder="URL da planilha ou Google Sheets" /><Button onClick={addSheet}>Vincular planilha</Button>{notice ? <p className="text-sm font-bold text-lime-700">{notice}</p> : null}</div><h3 className="mt-8 font-display text-lg font-bold">Feedbacks recentes</h3><div className="mt-3 max-h-52 space-y-2 overflow-y-auto">{feedbacks.map(item => <div key={item.id} className="rounded-xl bg-sand/60 p-3 text-xs"><strong>{item.user.name}</strong> · cansaço {item.fatigueLevel}/10 · dores {item.jointPainLevel}/10<p className="mt-1 text-ink/55">{item.message || 'Sem comentário'}</p></div>)}</div></Panel></div>;
}
