import Link from 'next/link';

const benefits = [
  ['Treino sob medida', 'Sua anamnese orienta a estrutura do plano e a seleção dos exercícios.'],
  ['Vídeos explicativos inclusos', 'Cada exercício vem com link direto para YouTube/Reels e execução orientada.'],
  ['Entrega via WhatsApp', 'Após a curadoria profissional, você recebe os arquivos de forma prática.']
];

export default function Home() { return <main>
  <nav className="container flex items-center justify-between py-6"><Link href="/" aria-label="EVOTrainer - início"><img src="/logo.svg" alt="EVOTrainer" className="h-10 w-auto" /></Link><Link href="/admin" className="text-sm text-gray-500 hover:text-gray-900">Área do personal →</Link></nav>
  <section className="container grid gap-10 py-16 md:grid-cols-[1.1fr_.9fr] md:items-center md:py-24">
    <div><p className="mb-5 text-sm font-bold uppercase tracking-[.2em] text-lime-700">EVOTrainer · curadoria profissional</p><h1 className="max-w-2xl text-5xl font-black leading-[.95] tracking-[-.05em] md:text-7xl">Uma planilha que respeita o seu ponto de partida.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-gray-600">Preencha sua anamnese. Um profissional registrado revisa suas respostas antes de liberar um plano prático para você treinar com segurança e constância.</p><Link href="/checkout" className="btn btn-dark mt-8 inline-block">Quero minha planilha por R$ 50,00 <span className="ml-2">↗</span></Link></div>
    <div className="card relative overflow-hidden bg-[#d9f36a] p-8 md:p-12"><div className="absolute -right-12 -top-12 h-40 w-40 rounded-full border-[24px] border-white/40"/><p className="text-sm font-bold uppercase tracking-[.18em]">Plano individual</p><div className="mt-16"><div className="text-6xl font-black tracking-[-.08em]">R$ 50<span className="text-3xl">,00</span></div><p className="mt-3 max-w-xs text-lg font-medium">valor fixo por planilha personalizada.</p></div><div className="mt-10 border-t border-black/15 pt-5 text-sm">✓ Curadoria profissional<br/>✓ Vídeos de execução<br/>✓ Entrega digital</div></div>
  </section>
  <section className="container grid gap-4 border-y border-gray-200 py-12 md:grid-cols-3">{benefits.map(([title, text], index) => <div key={title} className="card p-6"><p className="text-xs font-bold text-lime-700">0{index + 1}</p><h2 className="mt-4 text-xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-gray-600">{text}</p></div>)}</section>
  <section className="container grid gap-8 py-16 md:grid-cols-[.8fr_1.2fr] md:items-center"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-lime-700">Sobre o profissional</p><h2 className="mt-3 text-3xl font-black tracking-tight">Conhecimento técnico por trás de cada curadoria.</h2></div><div className="card bg-white p-7"><h3 className="text-xl font-bold">Felipe Cordeiro Ferreira</h3><p className="mt-3 text-sm leading-7 text-gray-600"><strong>Registro Profissional:</strong> CREF 071550/RJ - Bacharel<br/><strong>Especialização:</strong> Pós-Graduado em Fisiologia do Exercício</p><p className="mt-4 text-sm leading-6 text-gray-600">A planilha é elaborada para fins educacionais e de orientação geral, considerando as informações fornecidas na anamnese e sujeita à revisão profissional.</p></div></section>
  <footer className="border-t border-gray-200 bg-white"><div className="container grid gap-8 py-10 text-sm text-gray-600 md:grid-cols-[1.4fr_1fr_1fr]"><div><strong className="text-lg text-gray-900">EVOTrainer</strong><p className="mt-3 max-w-sm leading-6">Planilhas de treino com curadoria profissional e responsabilidade.</p><p className="mt-4 text-xs">CNPJ/CPF: inserir identificação empresarial<br/>Responsável: Felipe Cordeiro Ferreira · CREF 071550/RJ - Bacharel</p></div><div><strong className="text-gray-900">Informações</strong><p className="mt-3"><a href="#" className="underline">Termos de Uso</a></p><p className="mt-2"><a href="#" className="underline">Política de Privacidade</a></p></div><div><strong className="text-gray-900">Compromisso</strong><p className="mt-3 inline-block rounded-full border border-gray-200 px-3 py-2 text-xs">✓ Pagamento Seguro</p><p className="mt-2 inline-block rounded-full border border-gray-200 px-3 py-2 text-xs">✓ Garantia de Curadoria Profissional</p></div></div><div className="container border-t border-gray-100 py-5 text-xs leading-5 text-gray-500">Aviso de saúde: este material não substitui avaliação médica ou acompanhamento individual presencial. Interrompa o exercício em caso de dor ou mal-estar e procure um profissional habilitado. A EVOTrainer não se responsabiliza por uso fora das orientações ou por informações incorretas fornecidas no formulário.</div></footer>
</main> }
