'use client';

import { Button, Notice, PageIntro, Panel } from '@/components/ui';
import { apiFetch } from '@/lib/api';
import { getSessionUser } from '@/lib/auth';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function AlunoPage() {
  const router = useRouter(); const user = getSessionUser();
  const [sheets, setSheets] = useState<any[]>([]); const [form, setForm] = useState({ fatigueLevel: 5, jointPainLevel: 0, loadDifficulty: 5, message: '' }); const [message, setMessage] = useState('');
  useEffect(() => { if (!user || user.role !== 'STUDENT') { router.replace('/login?next=/aluno'); return; } void apiFetch<{ spreadsheets: any[] }>(`/spreadsheets/${user.id}`).then(data => setSheets(data.spreadsheets)).catch(() => undefined); }, [router, user]);
  async function sendFeedback() { if (!user) return; try { await apiFetch('/feedbacks', { method: 'POST', body: JSON.stringify({ ...form, userId: user.id }) }); setMessage('Feedback enviado. Sua equipe já pode acompanhar sua evolução.'); setForm({ fatigueLevel: 5, jointPainLevel: 0, loadDifficulty: 5, message: '' }); } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível enviar.'); } }
  return <main className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><PageIntro eyebrow="Área do aluno" title={`Olá, ${user?.name ?? ''}`} description="Acompanhe seus treinos, materiais e evolução em um só lugar." action={<Button variant="dark" onClick={() => router.push('/treino')}>Abrir meus treinos</Button>} /><div className="grid gap-5 md:grid-cols-3">{['Treino A', 'Treino B', 'Treino C'].map((title, index) => <Panel key={title} className="p-6"><p className="text-xs font-black uppercase tracking-wider text-lime-700">Semana de treino</p><h2 className="mt-2 font-display text-2xl font-bold">{title}</h2><p className="mt-2 text-sm text-ink/50">Consulte sua planilha e registre a execução.</p><a href="/treino" className="mt-5 inline-block font-bold text-lime-700">Ver treino →</a></Panel>)}</div><div className="mt-7 grid gap-7 lg:grid-cols-2"><Panel className="p-6"><h2 className="font-display text-2xl font-bold">Minhas Planilhas</h2><div className="mt-5 space-y-3">{sheets.length === 0 ? <p className="text-sm text-ink/50">Suas planilhas oficiais aparecerão aqui.</p> : sheets.map(sheet => <div key={sheet.id} className="flex items-center justify-between rounded-2xl bg-sand/60 p-4"><span className="font-bold">{sheet.title}</span><a className="font-bold text-lime-700" href={sheet.fileUrl || sheet.externalUrl} target="_blank" rel="noreferrer">Abrir / baixar</a></div>)}</div></Panel><Panel className="p-6"><h2 className="font-display text-2xl font-bold">Feedback da semana</h2><div className="mt-5 grid gap-4 sm:grid-cols-3">{([['fatigueLevel', 'Cansaço'], ['jointPainLevel', 'Dores'], ['loadDifficulty', 'Dificuldade']] as const).map(([field, label]) => <label key={field} className="text-sm font-bold">{label}<input className="mt-2 w-full" type="range" min={field === 'jointPainLevel' ? 0 : 1} max="10" value={form[field]} onChange={e => setForm({ ...form, [field]: Number(e.target.value) })} /><span className="text-lime-700">{form[field]}/10</span></label>)}</div><textarea className="field-control mt-5 min-h-24" placeholder="Conte como foi sua semana..." value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} />{message ? <div className="mt-4"><Notice kind={message.startsWith('Feedback') ? 'success' : 'error'}>{message}</Notice></div> : null}<Button className="mt-4" onClick={sendFeedback}>Enviar feedback</Button></Panel></div></main>;
}
