'use client';

import { Button, Notice, Panel } from '@/components/ui';
import { apiFetch } from '@/lib/api';
import { saveSession } from '@/lib/auth';
import { useRouter, useSearchParams } from 'next/navigation';
import { FormEvent, Suspense, useState } from 'react';

function LoginForm() {
  const router = useRouter(); const params = useSearchParams(); const [recovery, setRecovery] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setNotice(''); setLoading(true); try { if (recovery) { const response = await apiFetch<{ message: string; resetToken?: string }>('/auth/forgot-password', { method: 'POST', body: JSON.stringify({ email }) }); setNotice(response.resetToken ? `${response.message} Token local: ${response.resetToken}` : response.message); } else { const response = await apiFetch<{ token: string; user: any }>('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); saveSession(response.token, response.user); router.push(params.get('next') || (response.user.role === 'ADMIN' ? '/admin' : '/aluno')); } } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível concluir.'); } finally { setLoading(false); } }
  return <main className="mx-auto max-w-lg px-5 py-16"><Panel className="p-7 md:p-10"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-300">Acesso à plataforma</p><h1 className="mt-2 font-display text-4xl font-bold text-white">{recovery ? 'Recupere sua senha' : 'Bem-vindo de volta'}</h1><p className="mt-3 text-sm text-slate-400">{recovery ? 'Informe seu e-mail para receber as instruções de redefinição.' : 'Entre para acessar seu acompanhamento personalizado.'}</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="block"><span className="field-label">E-mail</span><input className="field-control" type="email" required value={email} onChange={e => setEmail(e.target.value)} /></label>{!recovery ? <label className="block"><span className="field-label">Senha</span><input className="field-control" type="password" required value={password} onChange={e => setPassword(e.target.value)} /></label> : null}{error ? <Notice kind="error">{error}</Notice> : null}{notice ? <Notice kind="success">{notice}</Notice> : null}<Button type="submit" loading={loading} className="w-full">{recovery ? 'Enviar instruções' : 'Entrar'}</Button><button type="button" className="w-full text-sm font-bold text-emerald-300" onClick={() => { setRecovery(!recovery); setError(''); setNotice(''); }}>{recovery ? 'Voltar para o login' : 'Esqueci minha senha'}</button>{!recovery ? <p className="text-center text-sm text-slate-400">Ainda não tem conta? <a className="font-bold text-emerald-300" href="/cadastro">Criar cadastro</a></p> : null}</form></Panel></main>;
}
export default function LoginPage() { return <Suspense fallback={<main className="p-12 text-center">Carregando...</main>}><LoginForm /></Suspense>; }
